<?php
require_once 'config/database.php';
$db = (new Database())->getConnection();
$tables = $db->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
$sql = "-- Database Export\n-- Generated by System\n\nSET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\nSTART TRANSACTION;\nSET time_zone = \"+00:00\";\n\n";
foreach ($tables as $table) {
    $sql .= "DROP TABLE IF EXISTS `$table`;\n";
    $create = $db->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
    $sql .= $create['Create Table'] . ";\n\n";
    
    // Fetch data
    $rows = $db->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
    if (count($rows) > 0) {
        $sql .= "INSERT INTO `$table` (";
        $keys = array_keys($rows[0]);
        $sql .= "`" . implode("`, `", $keys) . "`) VALUES \n";
        $values = [];
        foreach ($rows as $row) {
            $rowValues = [];
            foreach ($row as $val) {
                if ($val === null) {
                    $rowValues[] = "NULL";
                } else {
                    $rowValues[] = "'" . addslashes($val) . "'";
                }
            }
            $values[] = "(" . implode(", ", $rowValues) . ")";
        }
        $sql .= implode(",\n", $values) . ";\n\n";
    }
}
$sql .= "COMMIT;\n";
file_put_contents('restaurant_db.sql', $sql);
echo "SQL Dump Successful!";
